services:
  photoprism:
    image: "${IMAGE:-photoprism/photoprism:latest}"
    container_name: "photoprism"
    restart: "always"
    networks:
      - "reverse-proxy"
    expose:
      - "2342"
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "https://photoprism.home.tastic"
      PHOTOPRISM_DISABLE_TLS: "true"
      PHOTOPRISM_DEFAULT_TLS: "false"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "none"
      PHOTOPRISM_WORKERS: 1
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"
      PHOTOPRISM_DISABLE_FACES: "true"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "true"
      PHOTOPRISM_DISABLE_VECTORS: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_BACKUP_ALBUMS: "true"
      PHOTOPRISM_BACKUP_DATABASE: "true"
      PHOTOPRISM_BACKUP_SCHEDULE: "daily"
      PHOTOPRISM_INDEX_SCHEDULE: ""
      PHOTOPRISM_AUTO_INDEX: 300
      PHOTOPRISM_AUTO_IMPORT: -1
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
    working_dir: "/photoprism"
    volumes:
      - "originals:/photoprism/originals"
      - "./storage:/photoprism/storage"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.entrypoints=websecure"
      - "traefik.http.routers.photoprism.rule=Host(`photoprism.home.tastic`)"
      - "homepage.group=Media & Entertainment"
      - "homepage.name=PhotoPrism"
      - "homepage.icon=photoprism.png"
      - "homepage.href=https://photoprism.home.tastic"
      - "homepage.description=AI-Powered Photo Management"
      - "homepage.widget.type=photoprism"
      - "homepage.widget.url=https://photoprism.home.tastic"
      - "homepage.widget.key=${PHOTOPRISM_APP_KEY}"

volumes:
  originals:
    driver_opts:
      type: cifs
      o: "noserverino,username=${NAS_USERNAME},password=${NAS_PASSWORD},iocharset=utf8"
      device: "//${NAS_URL}/${NAS_SHARE_NAME}"

networks:
  reverse-proxy:
    external: true
